# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0e63784bd8351ee18c3b0a7e4dbb8f57631edd146451545fb778aacf9a80519661f3a7bca8b057499eb13677e633116b8addb3f009df37954adeef049f2a42f

test:
  secret_key_base: cf5586626d80fee45bb44a6676b8c58dbfc92437638d138c91b6f98b594039788c56fdafcaf90afb36adfb8c6c938a251d358483cba2df753ea5f11ccb0fe1fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
